Check Grafana rootUrls also

diff --git a/iiris-build b/iiris-build
--- a/iiris-build
+++ b/iiris-build
@@ -29,6 +29,11 @@ if [ -z "$GRAFANA_ACCESS_POLICY_TOKEN" ]; then
   exit 1
 fi
 
+if [ -z "$GRAFANA_ROOT_URLS" ]; then
+  echo "ERROR: Grafana root URLs missing. Token must be exported in GRAFANA_ROOT_URLS environment variable!"
+  exit 1
+fi
+
 # Note that build is done inside Docker container so that the distro matches Grafana distro
 # If the build was done in Alma Linux host the distro would be different and the binaries compiled by Go would not work
 # Build
