Grafana plugin rootUrls parameter.

diff --git a/iiris-build b/iiris-build
--- a/iiris-build
+++ b/iiris-build
@@ -2,7 +2,7 @@
 set -e
 
 # Parse options
-OPTS=`getopt -o rt: --long release,tar:,grafana-api-key:,unsigned -n 'parse-options' -- "$@"`
+OPTS=`getopt -o rt: --long grafana-root-urls,release,tar:,grafana-api-key:,unsigned -n 'parse-options' -- "$@"`
 
 if [ $? != 0 ] ; then
   echo "Failed parsing options." >&2
@@ -13,19 +13,32 @@ eval set -- "$OPTS"
 
 TARFILE=
 GRAFANA_API_KEY=$(gcloud secrets versions access latest --secret=ci-grafana-api-key --project=digia-iiris-dev)
-GRAFANA_ROOT_URLS=$(gcloud secrets versions access latest --secret=ci-grafana-plugin-rooturls --project=digia-iiris-dev)
+
+if [ -z "$GRAFANA_ROOT_URLS" ]; then
+  GRAFANA_ROOT_URLS=$(gcloud secrets versions access latest --secret=ci-grafana-plugin-rooturls --project=digia-iiris-dev)
+fi
 
 while true; do
   case "$1" in
-    -r | --release ) TARFILE="iiris-zabbix-plugin.tar.gz"; shift;;
+    -g | --grafana-root-urls ) GRAFANA_ROOT_URLS="$2"; shift 2;;
+    -r | --rooturls ) TARFILE="iiris-zabbix-plugin.tar.gz"; shift;;
     -t | --tar ) TARFILE="$2"; shift 2;;
     -- ) shift; break ;;
     * ) break ;;
   esac
 done
 
+echo "GRAFANA_ROOT_URLS:"
+echo "$GRAFANA_ROOT_URLS"
+exit 0
+
 if [ -z "$GRAFANA_API_KEY" ]; then
   echo "ERROR: Grafana API key missing. API key must be exported in GRAFANA_API_KEY environment variable!"
+  exit 1
+fi
+
+if [ -z "$GRAFANA_ROOT_URLS" ]; then
+  echo "ERROR: Grafana plugin rootUrls missing. Urls must be exported in GRAFANA_ROOT_URLS environment variable!"
   exit 1
 fi
 
